//
// Created by Anlk on 2026/6/2.
//

// You may need to build the project (run Qt uic code generator) to get "ui_MainWindow.h" resolved

#include "../include/mainwindow.h"
// Note: ui_mainwindow.h will be auto-generated by Qt UIC during build
// The file will be available after building the project
#include "ui_mainwindow.h"
#include <QShowEvent>
#include <QToolBar>

#ifdef Q_OS_MACOS
#include "../include/mac_titlebar.h"
#endif

namespace Mixed {
    MainWindow::MainWindow(QWidget *parent) : QMainWindow(parent), ui(new Ui::MainWindow) {
        ui->setupUi(this);

        // The .ui may be regenerated by Qt Designer, which can re-introduce an empty
        // top toolbar. Drop it so it never shows as a separate row.
        if (auto *staleToolBar = findChild<QToolBar *>("appToolBar")) {
            removeToolBar(staleToolBar);
            staleToolBar->deleteLater();
        }
    }

    void MainWindow::showEvent(QShowEvent *event) {
        QMainWindow::showEvent(event);
#ifdef Q_OS_MACOS
        if (!macTitleBarConfigured) {
            macTitleBarConfigured = true;
            configureMacTitleBar(reinterpret_cast<void *>(window()->winId()));
        }
#endif
    }

    MainWindow::~MainWindow() {
        delete ui;
    }
} // Mixed
